CREATE TABLE Majors (
	MajorID INT IDENTITY PRIMARY KEY NOT NULL,
	[Name] VARCHAR(50) NOT NULL
	);
CREATE TABLE Students (
	StudentID INT IDENTITY PRIMARY KEY NOT NULL,
	StudentNumber INT UNIQUE NOT NULL,
	StudentName VARCHAR(50) NOT NULL,
	MajorID INT REFERENCES Majors(MajorID)
	);
CREATE TABLE Payments (
	PaymentID INT IDENTITY PRIMARY KEY NOT NULL,
	PaymentDate DATE NOT NULL,
	PaymentAmount DECIMAL(6,2) NOT NULL,
	StudentID INT REFERENCES Students(StudentID)
	);
CREATE TABLE Subjects (
	SubjectID INT IDENTITY PRIMARY KEY NOT NULL,
	SubjectName VARCHAR(50) NOT NULL
	);
CREATE TABLE Agenda (
	StudentID INT REFERENCES Students(StudentID),
	SubjectID INT REFERENCES Subjects(SubjectID),
	CONSTRAINT PK_STUDENT_SUBJECT PRIMARY KEY (StudentID, SubjectID)
	);