--CREATE DATABASE RelationsExercise
--GO
--USE RelationsExercise

CREATE TABLE Passports(
	PassportID INT IDENTITY(101,1) PRIMARY KEY NOT NULL, 
	PassportNumber VARCHAR(20) NOT NULL
	)

CREATE TABLE Persons (
	PersonID INT IDENTITY NOT NULL,
	FirstName VARCHAR(20) NOT NULL,
	Salary DECIMAL(8,2), 
	PassportID INT NOT NULL
	)

INSERT INTO Passports VALUES
	('N34FG21B'), ('K65LO4R7'), ('ZE657QP2')

INSERT INTO Persons VALUES
	('Roberto', 43300.00, 102),
	('Tom', 56100.00, 103),
	('Yana', 60200.00, 101)

ALTER TABLE Persons
ADD CONSTRAINT PK_Id PRIMARY KEY (PersonID)

ALTER TABLE Persons
ADD CONSTRAINT FK_PassportID FOREIGN KEY (PassportID) REFERENCES Passports(PassportID)

ALTER TABLE Persons
ADD UNIQUE (PassportID)
