--CREATE DATABASE Store
--USE Store
CREATE TABLE ItemTypes (
	ItemTypeID INT IDENTITY PRIMARY KEY NOT NULL,
	[Name] VARCHAR(50) NOT NULL
	);
CREATE TABLE Items (
	ItemID INT IDENTITY PRIMARY KEY NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	ItemTypeID INT REFERENCES ItemTypes(ItemTypeID) NOT NULL
	);
CREATE TABLE Cities (
	CityID INT IDENTITY PRIMARY KEY NOT NULL,
	[Name] VARCHAR(50) NOT NULL
	);
CREATE TABLE Customers (
	CustomerID INT IDENTITY PRIMARY KEY NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	Birthday DATE,
	CityID INT REFERENCES Cities(CityID) NOT NULL
	);
CREATE TABLE Orders (
	OrderID INT IDENTITY PRIMARY KEY NOT NULL,
	CustomerID INT REFERENCES Customers(CustomerID)
	);
CREATE TABLE OrderItems (
	OrderID INT REFERENCES Orders(OrderID),
	ItemID INT REFERENCES Items(ItemID),
	CONSTRAINT PK_ORDER_ITEM PRIMARY KEY (OrderID, ItemID)
	);
