CREATE TABLE Planes (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	[Name] VARCHAR(30) NOT NULL,
	Seats INT NOT NULL,
	[Range] INT NOT NULL)
CREATE TABLE Flights (
	Id INT IDENTITY PRIMARY KEY,
	[DepartureTime] DATETIME,
	[ArrivalTime] DATETIME,
	Origin VARCHAR(50) NOT NULL,
	Destination VARCHAR(50) NOT NULL,
	PlaneId INT REFERENCES Planes(Id) NOT NULL)
CREATE TABLE Passengers (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	FirstName VARCHAR(30) NOT NULL,
	LastName VARCHAR(30) NOT NULL,
	Age INT NOT NULL,
	Address VARCHAR(30) NOT NULL,
	PassportId CHAR(11) NOT NULL)
CREATE TABLE LuggageTypes (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	[Type] VARCHAR(30) NOT NULL)
CREATE TABLE Luggages (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	LuggageTypeId INT REFERENCES LuggageTypes(Id) NOT NULL,
	PassengerId INT REFERENCES Passengers (Id) NOT NULL)
CREATE TABLE Tickets (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	PassengerId INT REFERENCES Passengers (Id) NOT NULL,
	FlightId INT REFERENCES Flights (Id) NOT NULL,
	LuggageId INT REFERENCES Luggages (Id) NOT NULL,
	Price DECIMAL(18,2) NOT NULL)