CREATE DATABASE SoftUni
USE SoftUni

CREATE TABLE Towns (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	[Name] VARCHAR(50) NOT NULL
	)

CREATE TABLE Addresses (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	AddressText VARCHAR(80) NOT NULL,
	TownId INT FOREIGN KEY REFERENCES Towns(Id) NOT NULL
	)
CREATE TABLE Departments (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	Name VARCHAR(50) NOT NULL
	)
CREATE TABLE Employees (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	FirstName VARCHAR(20) NOT NULL,
	MiddleName VARCHAR(20),
	LastName VARCHAR(20) NOT NULL,
	JobTitle VARCHAR(30) NOT NULL,
	DepartmentId INT FOREIGN KEY REFERENCES Departments(Id) NOT NULL,
	HireDate DATETIME NOT NULL,
	Salary DECIMAL(10,2) NOT NULL,
	AddressId INT FOREIGN KEY REFERENCES Addresses(Id) NOT NULL
	)
USE master
DROP DATABASE SoftUni
