CREATE TABLE Planets (
	Id INT IDENTITY PRIMARY KEY NOT NULL, 
	[Name] VARCHAR(30) NOT NULL)
CREATE TABLE Spaceports (
	Id INT IDENTITY PRIMARY KEY NOT NULL, 
	[Name] VARCHAR(50) NOT NULL,
	PlanetId INT REFERENCES Planets(Id) NOT NULL)
CREATE TABLE Spaceships (
	Id INT IDENTITY PRIMARY KEY NOT NULL, 
	[Name] VARCHAR(50) NOT NULL,
	Manufacturer VARCHAR(30) NOT NULL,
	LightSpeedRate INT DEFAULT 0)
CREATE TABLE Colonists (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	FirstName VARCHAR(20) NOT NULL,
	LastName VARCHAR(20) NOT NULL,
	Ucn VARCHAR(10) UNIQUE NOT NULL,
	BirthDate DATE NOT NULL)
CREATE TABLE Journeys (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	JourneyStart DATETIME NOT NULL,
	JourneyEnd DATETIME NOT NULL,
	Purpose VARCHAR(11) CHECK (Purpose IN ('Medical', 'Technical', 'Educational', 'Military')) NULL,
	DestinationSpaceportId INT REFERENCES Spaceports(Id) NOT NULL,
	SpaceshipId INT REFERENCES Spaceships(Id) NOT NULL)
CREATE TABLE TravelCards (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	CardNumber CHAR(10) UNIQUE NOT NULL,
	JobDuringJourney VARCHAR(8) CHECK (JobDuringJourney IN ('Pilot', 'Engineer', 'Trooper', 'Cleaner', 'Cook')) NULL,
	ColonistId INT REFERENCES Colonists(Id) NOT NULL,
	JourneyId INT REFERENCES Journeys(Id) NOT NULL)