CREATE TABLE Students (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	MiddleName NVARCHAR(50),
	LastName NVARCHAR(50) NOT NULL,
	Age TINYINT CHECK (Age>0),
	[Address] NVARCHAR(50),
	Phone NCHAR(10))
CREATE TABLE Subjects (
	Id INT IDENTITY PRIMARY KEY,
	[Name] NVARCHAR(20) NOT NULL,
	Lessons INT CHECK(Lessons>0) NOT NULL)
CREATE TABLE StudentsSubjects (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	StudentId INT REFERENCES Students (Id) NOT NULL,
	SubjectId INT REFERENCES Subjects (Id) NOT NULL,
	Grade DECIMAL(10,2) CHECK (Grade BETWEEN 2 AND 6) NOT NULL)
CREATE TABLE  Exams (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	[Date] DATETIME,
	SubjectId INT REFERENCES Subjects (Id) NOT NULL)
CREATE TABLE StudentsExams (
	StudentId INT REFERENCES Students (Id) NOT NULL,
	ExamId INT REFERENCES Exams(Id) NOT NULL,
	Grade DECIMAL(10,2) CHECK (Grade BETWEEN 2 AND 6) NOT NULL,
	CONSTRAINT PK_StudentsExams PRIMARY KEY ( StudentId, ExamId) )
CREATE TABLE Teachers (
	Id INT IDENTITY PRIMARY KEY NOT NULL,
	FirstName NVARCHAR(20) NOT NULL,
	LastName NVARCHAR(20) NOT NULL,
	[Address] NVARCHAR(20) NOT NULL,
	Phone NCHAR(10),
	SubjectId INT REFERENCES Subjects(Id) NOT NULL)
CREATE TABLE StudentsTeachers (
	StudentId INT REFERENCES Students(Id) NOT NULL,
	TeacherId INT REFERENCES Teachers(Id) NOT NULL,
	CONSTRAINT PK_StudentsTeachers PRIMARY KEY (StudentId,TeacherId))